### ISSUE TITLE
Export to PDF

### ISSUE THREAD

**Issue by karchjd** [kinimesi/cytoscape-svg#11]
Hey, thanks for this great package; it still works well for me. I would also like to export as PDF, specifically a PDF that contains only the SVG file. I assume this should be relatively easy, but I failed to do it myself. I mostly tried using https://github.com/yWorks/svg2pdf.js.

**Comment by kinimesi** [comment]
I don't think this should be part of this library, but I added examples to the demo files about saving the exported SVG as a PDF: https://github.com/kinimesi/cytoscape-svg/blob/114bbdf3f18e6f15e246317c4d63e7aa67d821b5/demo.html#L116

**Comment by karchjd** [comment]
Thanks a lot!
