### ISSUE TITLE
Ability to drag and drop svg images

### ISSUE THREAD

**Issue by KevinZhou1** [kinimesi/cytoscape-svg#2]
Is it possible to drag and drop the svg node images after the svg has been made?

**Comment by kinimesi** [comment]
I'm not sure if I understood your question, but the extension returns contents of the SVG and you can do whatever you want with it.

**Comment by KevinZhou1** [comment]
I would like to implement a feature of dragging the elements of the svg, similar to what is shown here: http://www.petercollingridge.co.uk/tutorials/svg/interactive/dragging/. 

However, it doesn't look that feasible without modifying the internals of the library that produces the svg

**Comment by kinimesi** [comment]
The produced SVGs are static.
