### ISSUE TITLE
Export nodeHTML content

### ISSUE THREAD

**Issue by invaders-xx** [kinimesi/cytoscape-svg#3]
Hi,

I am using the plugin cytoscape-node-html-label to display information in nodes. When I export the graph using your library I loose the content of those nodes. Is there any way to export those information ?

Many thanks in advance,

David

**Comment by kinimesi** [comment]
cytoscape-node-html-label doesn't add the information to the Cytoscape canvas, the information is added as HTML elements. Therefore, it isn't possible to export it with the extension which exports the canvas. Exporting it as png, or jpeg doesn't work either.
