### ISSUE TITLE
background color

### ISSUE THREAD

**Issue by KonradHoeffner** [kinimesi/cytoscape-svg#4]
Is there a way to set the background color? My application has a black background but the SVG gets exported with a white background.

**Comment by kinimesi** [comment]
There is, but it wasn't documented and not working properly. Fixed in the latest version and added it to the README. Here is an [example](https://kinimesi.github.io/cytoscape-svg/demo.html)

You can setup the background color with the `bg` [option](https://github.com/kinimesi/cytoscape-svg#api).
