### ISSUE TITLE
Add element's id in SVG

### ISSUE THREAD

**Issue by Jmedjid** [kinimesi/cytoscape-svg#5]
Hi !

After exporting the graph to svg, we observe that there is no id for the different elements which makes their selection difficult.
Would it be possible to include specific identifiers for each of them  ?

**Comment by kinimesi** [comment]
@Jmedjid this is not possible with the current implementation. We use [canvas2svg](https://github.com/kinimesi/canvas2svg) to convert the Cytoscape canvas into SVG. It might be possible to modify the methods in the canvas2svg library to take the ID as a parameters, but it'd require significant amount of work. Feel free to look into it, and make a PR if you figure it out.

Thanks!
