### ISSUE TITLE
'edge-text-rotation': 'autorotate' breaks colors

### ISSUE THREAD

**Issue by KonradHoeffner** [kinimesi/cytoscape-svg#7]
As soon as I display any labels using `'edge-text-rotation': 'autorotate'`, the SVG loses all colors and just becomes black and white. See the attached image of a correctly displayed and an incorrectly displayed image. As soon as I remove the edge text rotation, it works again.

![svg-autorotate-bug](https://user-images.githubusercontent.com/839577/108381936-99c40f80-7208-11eb-8335-62e0588a443d.png)

## Selector

```
  {
      'selector': 'edge',
      'css':
      {
        'z-compound-depth': 'bottom',
        'width': 2.0,
        'edge-text-rotation': 'autorotate',
        'label': function(edge)
        {
          return "bla";
        },
}
```

**Comment by rob-gordon** [comment]
I forked this repo in hopes of fixing this but realized this uses https://github.com/gliffy/canvas2svg under the hood and I wasn't really ready to dig into that.

I wrote a temporary fix for my case which uses [DOMParser](https://developer.mozilla.org/en-US/docs/Web/API/DOMParser) to edit the generated svg and patch the missing fill colors. Maybe it will work for your use case? You may have to adjust the fill color accordingly.

```
const svgStr = cy.current.svg({ full: true, scale: 2 });
const domparser = new DOMParser();
let svgEl = domparser.parseFromString(svgStr, "image/svg+xml");
let squares = [...svgEl.children[0].querySelectorAll("path")].filter(
  (x) =>
    !x.getAttribute("fill") &&
    x.getAttribute("paint-order") === "fill stroke markers"
);
squares = [...squares, ...svgEl.children[0].querySelectorAll("rect")];
squares.forEach((el) => el.setAttribute("fill", "#ffffff")); // <- set appropriate fill color here
const correctedSvgStr = svgEl.documentElement.outerHTML;
```

**Comment by kinimesi** [comment]
It looks like once the rotation of text is set, all parameters of existing nodes are reset. This is the commit that causes this issue: https://github.com/gliffy/canvas2svg/commit/c7df7fa81e9d8b392d0fc2a894f72af7ba54e306 I revered it in my fork: https://github.com/kinimesi/canvas2svg/commit/68b8ef886ca066d07294d9ee3157f6a3a9e44599 It looks like it works, but I'm not exactly sure if it breaks something else. I pushed the fixed version to unstable branch. Could you please test it and let me know if it works?

**Comment by karasma3** [comment]
Hello @kinimesi .
I tried your fork and it looks like it is  #working!
Other entities of the graph are not affected by this forked repo.

It looks like not only text-rotation: autorotate, but whole text-rotation attribute is not working.
Node and links to be shown:
![svgBefore](https://user-images.githubusercontent.com/17758032/129025989-45bf854c-5ce7-4b0c-aac3-404a1c486ee5.png)
Master branch:
![svgAfter](https://user-images.githubusercontent.com/17758032/129026021-d6e0af4b-fbac-46d2-a991-a2c24d04c8ef.png)
and the result with the fork:
![svgFork](https://user-images.githubusercontent.com/17758032/129026050-51078001-3fb7-4db7-a697-6bb336ac7719.png)

Can you propose the pull request to the canvas2svg? Or perhaps make cytoscape-svg dependant on your forked fix?

Best regards,
Maroš

**Comment by kinimesi** [comment]
Hi @karasma3, I'm confused by this: `It looks like not only text-rotation: autorotate, but whole text-rotation attribute is not working.` Does the fix solve all of these issues?

**Comment by KonradHoeffner** [comment]
Is there an update on this?

**Comment by kinimesi** [comment]
Hi, could you please try [v0.4.0](https://github.com/kinimesi/cytoscape-svg/tree/v0.4.0) and let me if it solves your problem?

**Comment by KonradHoeffner** [comment]
Yes, it works, thanks a lot!
